version: 2
#workflows:
jobs:
# dockerize:
 #  machine: true
 build:
  docker:
   
  # steps:
    # - checkout
     # Login to docker
    # - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t $DOCKER_USER/myapp:myimage .

     # deploy the image
     - run: docker push $DOCKER_USER/myapp:myimage

